In [2]:
import random as rand

In [17]:
# 문제 91
totalScore = []
for j in range(7):
    classScore = []
    for k in range(30):
        scores = []
        for i in range(5):
            scores.append(rand.randint(1, 100))
        classScore.append(scores)
    totalScore.append(classScore)

index = 1
maxinClass = []
avgClass= []
for t in totalScore:
    each = []
    for c in t:
        each.append(sum(c)//len(c))
        maxinClass.append(max(c))
    print(index,'반')
    print('평균 : ',sum(each)//len(each))
    avgClass.append(sum(each)//len(each))
    print('1등 : ',maxinClass[index-1])
    index+=1

print('------------')
print('전교평균 : ',sum(avgClass)//len(avgClass))


1 반
평균 :  49
1등 :  99
2 반
평균 :  45
1등 :  93
3 반
평균 :  48
1등 :  100
4 반
평균 :  53
1등 :  89
5 반
평균 :  53
1등 :  99
6 반
평균 :  49
1등 :  91
7 반
평균 :  49
1등 :  93
------------
전교평균 :  49


In [29]:
#문제 93

page = ['BCBAEBCE','ABCABCABC','ABCDABEABCDE','ABCEDF','ABCDABEA']
frame = [3,3,4,0,3]
def process(page, frame):
    if frame == 0:
        return len(page)*6
    stack = []
    count = 0
    for p in page:
        if p in stack:
            count+=1
        else:
            count+=6
            if len(stack)==frame:
                stack.pop(0)
            stack.append(p)
    return count

for p,f in zip(page,frame):
    print(process(p,f))
    


38
24
62
36
43


In [33]:
#문제 94
page = ['BCBAEBCE','ABCABCABC','ABCEDF']
frame = [3,3,0]
def LRU(page,frame):
    stack = []
    count = 0
    if frame == 0:
        return len(page)*6
    for p in page:
        if p in stack:
            count+=1
            stack.append(stack.pop(stack.index(p)))
        else:
            if len(stack) >= frame:
                stack.pop(0)
            stack.append(p)
            count+=6
    return count
for p,f in zip(page,frame):
    print(LRU(p,f))

33
24
36


In [34]:
import numpy as np

In [55]:
#문제 95
stamp = [
[1,1,1,2],
[2,0,0,0],
[1,1,1,1],
[0,0,0,0]
]
result = np.array(stamp)
rotate = 1
def rot(stamp):
    temp = [[0]*len(stamp) for _ in range(len(stamp))]
    print(temp)
    for i in range(len(stamp)):
        for j in range(len(stamp)):
            temp[j][len(stamp)-i-1] = stamp[i][j]
    return temp

for i in range(rotate):
    stamp = rot(stamp)
    
sumset = np.array(stamp)
for t in result+sumset:
    print(t)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[1 2 3 3]
[2 1 0 1]
[1 2 1 2]
[0 1 0 2]


In [69]:
# 문제 96
farm = [[0,0,0,0,0],[0,1,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0]]

for f in farm:
    print(f)
farmS = np.array(farm)
def findPlace(farm):
    N= len(farm)
    for i in range(N,0,-1):
        for j in range(N-i):
            for k in range(N-i):
                if 1 not in farmS[j:j+i+1,k:k+i+1]:
                    print(j,k)
                    return [i,j,k] #i : 밭 크기 j: 밭 시작점
            
newFarm = farm.copy()
n,startx,starty = findPlace(farmS)
for i in range(n+1):
    for j in range(n+1):
        newFarm[startx+i][starty+j] = '#'

for n in newFarm:
    print(n)

[0, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]
0 2
[0, 0, '#', '#', '#']
[0, 1, '#', '#', '#']
[0, 1, '#', '#', '#']
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]


In [ ]:
#문제 97
